import { useEffect } from 'react';
import { getPendingReports, deletePendingReport } from '../utils/offlineStorage';
import { reportingApi } from '../api';

export const useOfflineSync = () => {
    useEffect(() => {
        const syncReports = async () => {
            if (!navigator.onLine) return;

            const pending = await getPendingReports();
            if (pending.length === 0) return;

            console.log(`📡 LUIT Sync: Found ${pending.length} pending reports. Uploading...`);

            for (const report of pending) {
                try {
                    // Remove id generated by IndexedDB before sending to API
                    const { id, ...reportData } = report;
                    await reportingApi.createReport(reportData);
                    await deletePendingReport(id);
                    console.log(`✅ LUIT Sync: Report ${id} synced successfully.`);
                } catch (err) {
                    console.error(`❌ LUIT Sync: Failed to sync report ${report.id}`, err);
                }
            }
        };

        window.addEventListener('online', syncReports);
        // Also try to sync on mount if online
        syncReports();

        return () => window.removeEventListener('online', syncReports);
    }, []);
};
